version: '3'

services:
  web:
    container_name: cl-challenge
    restart: always
    build: .
    ports:
      - "8080:3000"
    links:
      - database
    volumes:
      - .:/usr/src/app

  database:
    container_name: mongo-challenge
    image: mongo
    ports:
      - "27018:27017"
